appname = api_MID
httpport= 9090
runmode = dev

autorender = false
copyrequestbody = true

origenes = http://localhost:4200

url_core          = http://localhost:8081
url_usuarios      = http://localhost:8082
url_empleo        = http://localhost:8083
url_catalogo      = http://localhost:8084
url_tienda        = http://localhost:8085
url_suscripciones = http://localhost:8086
url_soporte       = http://localhost:8087

